language: go
env:
- GIMME_CGO_ENABLED=1
go:
- master
os:
- osx
before_install:
- wget http://crossgcc.rts-software.org/download/gcc-4.8.1-for-linux32-linux64/gcc-4.8.1-for-linux64.dmg
- hdiutil attach gcc-4.8.1-for-linux64.dmg
- cd /Volumes/gcc-4.8.1-for-linux64
- sudo installer -pkg gcc-4.8.1-for-linux64.pkg -target "/"
- cd ${TRAVIS_BUILD_DIR}
- export PATH="${PATH}:/usr/local/gcc-4.8.1-for-linux64/bin"
- wget http://crossgcc.rts-software.org/download/gcc-4.8.1-for-linux32-linux64/gcc-4.8.1-for-linux32.dmg
- hdiutil attach gcc-4.8.1-for-linux32.dmg
- cd /Volumes/gcc-4.8.1-for-linux32
- sudo installer -pkg gcc-4.8.1-for-linux32.pkg -target "/"
- cd ${TRAVIS_BUILD_DIR}
- export PATH="${PATH}:/usr/local/gcc-4.8.1-for-linux32/bin"
before_script:
- make clean
- make dep-install
- make deps
- make cross-build
- make dist
- make 
script:
- bin/dntk --version
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: PiyrDGGfzpLQDwNfZWnoSuu9uCjiK1Ump5Oy+IMc1CzWPGy18FuZcnI6RttxBGd3amZlUPGG2mh0/sc2+Bs8AXScHuY3OQRxSF4xSKchB4eoEzJMLqAXAOe9aF8QFOICfSLz1kDMtHWydrRHwMJuTzEwKcO43ktICT1GNwCWOWdNheYuwE1unFlBc1PXxNex+ywYzluV3uVuuX8Vw3D0ZZML0hpxUw6NOuhxyHraR64bGR+Jo/O20XELwKZB8i/A4y62SbYiGmFf04rWQeK3is2NFTEdxlQE+hCqJGzFxgnN7KP0zJfkVNrsUM6ALHcA0K1dH2xJKco8ozpdqeEU9SdPO9m1aNRwoZbZjg3z6YNtjL1/WswfTpvECTZhOX/LDs4s2VdBk3uNPKqbnjs/fv8QiXkZaqEmMgFGc7sDjXN8C0KY5OdVShzoo8eFZvI3nSDkDpG2lR4keAnD8eTnaQd9VZLO0b7SOoIxPJ5KzEqbstHUosCt5e0zs1FgA5b6dDpnKoDK6Oyp75tcyASh1IPt0hdL01pdxBIdOiHfRpHCRswCu8FCYhsBzwz2BHy6P2OxfAjw+x01/tzjsBBueBN2hF1GH7M3oHM9gzZY8WIIxZJ1JxyJj+450xHaYmSrJDR/wC9AGfSTxzGhp4RMlWsF3oRI+xo9I1V3PxK1Vno=
  file: "./dist/*.{tar.gz,zip}"
  on:
    tags: true
