[package]
name = "dntk"
version = "2.0.3"
authors = ["nnao45 <n4sekai5y@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Command line's Interactive calculator, GNU bc wrapper."
readme = "README.md"
homepage = "https://github.com/nnao45/dntk"
repository = "https://github.com/nnao45/dntk"
keywords = ["cli", "rust", "bc"]
categories = ["command-line-utilities"]

[dependencies]
libc = "0.2"
bc = "0.1"
scopeguard = "1.0.0"
atty = "0.2"
clap = "2.20.3"